services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3009:3000"
    environment:
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=sachita67
      - DATABASE_NAME=ecommerce
      - JWT_SECRET=secret
      - CLOUDINARY_CLOUD_NAME=dfrb6f1sr
      - CLOUDINARY_API_KEY=123456789012345
      - CLOUDINARY_API_SECRET=M93Emu5npQ7jhDu5f_Gv-2SpJhY

  db:
    image: postgres:15-alpine
    environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=sachita67
       - POSTGRES_DB=ecommerce
    ports:
       - "54323:5432"
    volumes:
       - db_data:/var/lib/postgresql/data
volumes:
  db_data:
    driver: local