services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3009:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_TYPE=postgres
      - DB_PASSWORD=sachita67
      - DB_USERNAME=user
      - DB_DATABASE=ecommerce
      - JWT_SECRET=secret
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}

  db:
    image: postgres:15-alpine
    environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=sachita67
       - POSTGRES_DB=ecommerce
    ports:
       - "12346:5432"
    volumes:
       - db_data_dev:/var/lib/postgresql/data
volumes:
  db_data_dev:
    driver: local