services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3009:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_TYPE=postgres
      - DB_PASSWORD=sachita67
      - DB_USERNAME=user
      - DB_DATABASE=app_db
      - DB_NAME=ecommerce
      - JWT_SECRET=secret
      - CLOUDINARY_CLOUD_NAME=dfrb6f1sr
      - CLOUDINARY_API_KEY=123456789012345
      - CLOUDINARY_API_SECRET=M93Emu5npQ7jhDu5f_Gv-2SpJhY

  db:
    image: postgres:15-alpine
    environment:
       - POSTGRES_USER=user
       - POSTGRES_PASSWORD=sachita67
       - POSTGRES_DB=ecommerce
    ports:
       - "12346:5432"
    volumes:
       - db_data_dev:/var/lib/postgresql/data
volumes:
  db_data_dev:
    driver: local